---
# file: inventories/group_vars/database.yml
logging_directory: postgresql
firewall:
  - { port: "postgres", direction: "in", policy: "allow", description: "Postgres" }

primary_db: mserver

db_users:
  - user: program
    database: "{{ primary_db }}"
    password: "{{ vault_db_password }}"
    host: "{{ subnet_mask }}"

db_replication:
  user: "replica"
  database: "all"
  password: "{{ vault_replica_password }}"
  host: "{{ subnet_mask }}"

master_host: "{{ hostvars[ groups.master[0] ].inventory_hostname }}"
subnet_mask: "{{ inventory_hostname }}/24"

db_storage_type: 'ssd'
random_page_cost_ssd: 1.1
random_page_cost_hdd: 4
effective_io_concurrency_ssd: 200
effective_io_concurrency_hdd: 2
max_connections: 100
shared_buffers: "{{ (ansible_memtotal_mb / 4) | round | int }}"
database:
  listen_port: 5432
  listen_address: "localhost, {{ inventory_hostname }}"
  max_connections: "{{ max_connections }}"
  timezone: "UTC"
  default_statistics_target: 100
  shared_buffers: "{{ shared_buffers }}MB"
  effective_cache_size: "{{ (ansible_memtotal_mb * 3 / 4) | round | int }}MB"
  maintenance_work_mem: "{{ (ansible_memtotal_mb / 16) | round | int }}MB"
  work_mem: "{{ ((ansible_memtotal_mb - shared_buffers|int) * 1024 / (3 * max_connections * ansible_processor_cores * ansible_processor_threads_per_core)) | round | int }}kB"
  random_page_cost: "{{ (db_storage_type == 'ssd') | ternary(random_page_cost_ssd, random_page_cost_hdd) }}"
  effective_io_concurrency:  "{{ (db_storage_type == 'ssd') | ternary(effective_io_concurrency_ssd, effective_io_concurrency_hdd) }}"
  checkpoint_completion_target: 0.7
  wal_buffers: "{{ (shared_buffers|int * 3 / 100) | round | int }}MB"
  min_wal_size: "1GB"
  max_wal_size: "2GB"