---
# file: roles/postgres/defaults/mail.yml
primary_db: mserver
conf_dir: /etc/postgresql/11/main
data_dir: /var/lib/postgresql/11/main
run_dir: /var/run/postgresql
db_users:
  - user: program
    database: "{{ primary_db }}"
    password: "{{ vault_db_password }}"
    host: "{{ subnet_mask }}"

db_replication:
  user: "replica"
  database: "all"
  password: "{{ vault_replica_password }}"
  host: "{{ subnet_mask }}"